server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      database: spitdb
      host: 192.168.150.134
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true